definitions:
  customer.Customer:
    properties:
      address:
        type: string
      bussiness_phone:
        type: string
      city:
        type: string
      company:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
    type: object
  customer.CustomersList:
    properties:
      data:
        items:
          $ref: '#/definitions/customer.Customer'
        type: array
      total_records:
        type: integer
    type: object
  customer.getCustomersRequest:
    properties:
      limit:
        type: integer
      offset:
        type: integer
    type: object
  employee.Employee:
    properties:
      address:
        type: string
      bussiness_phone:
        type: string
      company:
        type: string
      email_address:
        type: string
      fax_number:
        type: string
      first_name:
        type: string
      home_phone:
        type: string
      id:
        type: integer
      job_title:
        type: string
      last_name:
        type: string
      mobile_phone:
        type: string
    type: object
  employee.EmployeeTop:
    properties:
      email_address:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      total_sellings:
        type: string
    type: object
  employee.EmployeesList:
    properties:
      data:
        items:
          $ref: '#/definitions/employee.Employee'
        type: array
      total_records:
        type: integer
    type: object
  employee.addEmployeeRequest:
    properties:
      address:
        type: string
      businessPhone:
        type: string
      company:
        type: string
      emailAddress:
        type: string
      faxNumber:
        type: string
      firstName:
        type: string
      homePhone:
        type: string
      jobTitle:
        type: string
      lastName:
        type: string
      mobilePhone:
        type: string
    type: object
  employee.getEmployeesRequest:
    properties:
      limit:
        type: integer
      offset:
        type: integer
    type: object
  employee.updateEmployeeRequest:
    properties:
      address:
        type: string
      businessPhone:
        type: string
      company:
        type: string
      emailAddress:
        type: string
      faxNumber:
        type: string
      firstName:
        type: string
      homePhone:
        type: string
      id:
        type: integer
      jobTitle:
        type: string
      lastName:
        type: string
      mobilePhone:
        type: string
    type: object
  product.Product:
    properties:
      category:
        type: string
      description:
        type: string
      id:
        type: integer
      listPrice:
        type: number
      productCode:
        type: string
      productName:
        type: string
      standardCost:
        type: number
    type: object
  product.ProductTop:
    properties:
      id:
        type: integer
      productCode:
        type: string
      productName:
        type: string
      sold:
        type: number
    type: object
  product.ProductTopResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/product.ProductTop'
        type: array
      totalSellings:
        type: number
    type: object
  product.ProductsList:
    properties:
      data:
        items:
          $ref: '#/definitions/product.Product'
        type: array
      totalRecords:
        type: integer
    type: object
  product.getAddProductRequest:
    properties:
      category:
        type: string
      description:
        type: string
      listPrice:
        type: number
      productCode:
        type: string
      productName:
        type: string
      standardCost:
        type: number
    type: object
  product.getProductsRequest:
    properties:
      limit:
        type: integer
      offset:
        type: integer
    type: object
  product.getUpdateProductRequest:
    properties:
      category:
        type: string
      description:
        type: string
      id:
        type: integer
      listPrice:
        type: number
      productCode:
        type: string
      productName:
        type: string
      standardCost:
        type: number
    type: object
info:
  contact:
    email: sevann.radhak@gmail.com
    name: Sevann Radhak
    url: http://github.com/sevannr
  description: This is a sample server celler developed with Golang and MariaDB
  license: {}
  title: Products with Golang - API
  version: "1.0"
paths:
  /customers/paginated:
    post:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: getCustomers
        required: true
        schema:
          $ref: '#/definitions/customer.getCustomersRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Paginate list of customers
          schema:
            $ref: '#/definitions/customer.CustomersList'
      summary: Customers list
      tags:
      - Customer
  /employees/:
    post:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: addEmployeeRequest
        required: true
        schema:
          $ref: '#/definitions/employee.addEmployeeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: New employee created
          schema:
            $ref: '#/definitions/employee.Employee'
      summary: Create new Employee
      tags:
      - Employee
    put:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: updateEmployeeRequest
        required: true
        schema:
          $ref: '#/definitions/employee.updateEmployeeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Employee updated
          schema:
            $ref: '#/definitions/employee.Employee'
      summary: Update an Emplyee
      tags:
      - Employee
  /employees/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Employee Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Employee
          schema:
            $ref: '#/definitions/employee.Employee'
      summary: Delete Emplyee by Id
      tags:
      - Employee
    get:
      consumes:
      - application/json
      parameters:
      - description: Employee Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Employee
          schema:
            $ref: '#/definitions/employee.Employee'
      summary: Emplyee by Id
      tags:
      - Employee
  /employees/best-seller:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Best Employee
          schema:
            $ref: '#/definitions/employee.EmployeeTop'
      summary: Best Emplyee
      tags:
      - Employee
  /employees/paginated:
    post:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: getEmployees
        required: true
        schema:
          $ref: '#/definitions/employee.getEmployeesRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Paginate list of employees
          schema:
            $ref: '#/definitions/employee.EmployeesList'
      summary: Emplyees list
      tags:
      - Employee
  /products:
    put:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: updateProductRequest
        required: true
        schema:
          $ref: '#/definitions/product.getUpdateProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Product updated
          schema:
            $ref: '#/definitions/product.Product'
      summary: Update Product
      tags:
      - Product
  /products/:
    post:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: addProductRequest
        required: true
        schema:
          $ref: '#/definitions/product.getAddProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: New product created
          schema:
            $ref: '#/definitions/product.Product'
      summary: Create new Product
      tags:
      - Product
  /products/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product deleted
          schema:
            $ref: '#/definitions/product.Product'
      summary: Delete Product by Id
      tags:
      - Product
    get:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product
          schema:
            $ref: '#/definitions/product.Product'
      summary: Get Product by Id
      tags:
      - Product
  /products/bestselling:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Top ten best selling products
          schema:
            $ref: '#/definitions/product.ProductTopResponse'
      summary: Get best selling Products
      tags:
      - Product
  /products/paginated:
    post:
      consumes:
      - application/json
      parameters:
      - description: User data
        in: body
        name: getProductsRequest
        required: true
        schema:
          $ref: '#/definitions/product.getProductsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Products paginated
          schema:
            $ref: '#/definitions/product.ProductsList'
      summary: Products list
      tags:
      - Product
swagger: "2.0"
